import type { GameTheme } from './themeTypes'

export const rainyCafeTheme: GameTheme = {
  id: 'rainy-cafe',
  displayName: 'Rainy Cafe',
  description: 'A warm window-side cafe table with soft rain, amber lamps, and muted blue evening light.',
  colors: {
    pageBackground: '#0f1718',
    canvasBackground: '#172224',
    panelBackground: '#ead1a2',
    panelBorder: '#4a2c1f',
    panelShadow: '#1f1510',
    woodDark: '#2d1b15',
    woodMid: '#6f4328',
    parchment: '#f0d7a7',
    mutedGreen: '#879168',
    rainyBlue: '#37586a',
    lightSquare: '#efd2a0',
    darkSquare: '#879168',
    accent: '#d8a344',
    text: '#302018',
  },
  assets: {
    background: '/src/assets/themes/rainy-cafe/backgrounds/room-placeholder.webp',
    vignetteLighting: '/src/assets/themes/rainy-cafe/backgrounds/vignette-lighting-placeholder.webp',
    rainParticles: '/src/assets/themes/rainy-cafe/particles/window-rain-placeholder.webp',
    boardFrame: '/src/assets/themes/rainy-cafe/boards/board-frame-placeholder.webp',
    boardSurface: '/src/assets/themes/rainy-cafe/boards/board-surface-placeholder.webp',
    lightSquare: '/src/assets/themes/rainy-cafe/boards/light-square-placeholder.webp',
    darkSquare: '/src/assets/themes/rainy-cafe/boards/dark-square-placeholder.webp',
    playerPanel: '/src/assets/themes/rainy-cafe/panels/player-panel-placeholder.webp',
    moveHistoryPanel: '/src/assets/themes/rainy-cafe/panels/move-history-panel-placeholder.webp',
    actionButtonBase: '/src/assets/themes/rainy-cafe/buttons/action-button-placeholder.webp',
    avatarFrame: '/src/assets/themes/rainy-cafe/avatars/avatar-frame-placeholder.webp',
    avatars: '/src/assets/themes/rainy-cafe/avatars/avatar-placeholder.webp',
    decor: '/src/assets/themes/rainy-cafe/decor/decor-placeholder.webp',
    ambientSound: '/src/assets/themes/rainy-cafe/sounds/rain-ambient-placeholder.mp3',
  },
  sounds: {
    ambient: 'rain-on-window',
    move: 'soft-wood-tap',
    capture: 'cup-clink',
  },
  particles: {
    id: 'soft-window-rain',
    description: 'Small diagonal rain streaks over the background layer.',
  },
  boardStyle: {
    frame: 'dark carved wood frame with leafy corner decor',
    pieceSet: 'placeholder classic unicode pieces until pixel pieces are imported',
  },
  panelStyle: {
    frame: 'stacked cream parchment panels with dark wood trim',
    surface: 'paper grain placeholder with leafy corner accents',
  },
  buttonStyle: {
    frame: 'large chunky cafe action buttons in muted green, amber, blue, and lilac',
    surface: 'stitched cloth and painted wood placeholder surfaces',
  },
  decorSlots: [
    { id: 'left-cup', label: 'Cup slot', placement: 'left' },
    { id: 'left-lamp', label: 'Lamp slot', placement: 'left' },
    { id: 'right-books', label: 'Book stack slot', placement: 'right' },
    { id: 'bottom-table-item', label: 'Table item slot', placement: 'bottom' },
    { id: 'window-decoration', label: 'Window decor slot', placement: 'background' },
  ],
}
